// Sections
export const SECTION_MAX_ANSWERS_COUNT = 10;
export const SECTION_MIN_CONTENT_LENGTH = 1;
export const SECTION_MAX_CONTENT_LENGTH = 4096;
export const SECTION_MIN_VARIANT_LENGTH = 1;
export const SECTION_MAX_VARIANT_LENGTH = 256;
export const SECTION_MIN_VARIANT_COUNT = 2;
export const SECTION_MAX_VARIANT_COUNT = 10;
